# Generated by Django 3.2.9 on 2021-12-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
    ]
