# Generated by Django 3.2.9 on 2021-12-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0003_auto_20211229_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='biography',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
