# Generated by Django 3.2.9 on 2021-12-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0004_profile_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
